import { useEffect, useState, type FormEvent } from 'react'
import * as Icons from 'lucide-react'
import { activities, buildingDetails, buildings, eventCalendar, eventReservations, eventSpaces, moduleMeta, navigation, serviceSync, stats } from './data'
import { demoAuth } from './services/auth'
import type { IconName, ModuleKey } from './types'

const iconMap: Record<IconName, Icons.LucideIcon> = {
  'layout-dashboard': Icons.LayoutDashboard, 'building-2': Icons.Building2, 'door-open': Icons.DoorOpen, users: Icons.Users,
  'file-text': Icons.FileText, 'credit-card': Icons.CreditCard, wrench: Icons.Wrench, warehouse: Icons.Warehouse,
  boxes: Icons.Boxes, 'arrow-left-right': Icons.ArrowLeftRight, 'clipboard-list': Icons.ClipboardList, truck: Icons.Truck,
  'shopping-cart': Icons.ShoppingCart, landmark: Icons.Landmark, 'book-open': Icons.BookOpen, 'bar-chart-3': Icons.BarChart3,
  'user-cog': Icons.UserCog, 'shield-check': Icons.ShieldCheck, settings: Icons.Settings, 'scroll-text': Icons.ScrollText,
  'calendar-days': Icons.CalendarDays, 'calendar-check-2': Icons.CalendarCheck2, mail: Icons.Mail, 'folder-open': Icons.FolderOpen,
  contact: Icons.Contact, 'party-popper': Icons.PartyPopper, 'calendar-range': Icons.CalendarRange, 'map-pinned': Icons.MapPinned, ticket: Icons.Ticket,
  'briefcase-business': Icons.BriefcaseBusiness, 'user-round-check': Icons.UserRoundCheck, 'clock-3': Icons.Clock3, 'calendar-off': Icons.CalendarOff,
  'wallet-cards': Icons.WalletCards, 'graduation-cap': Icons.GraduationCap, 'clipboard-check': Icons.ClipboardCheck,
}

function IntroScreen() {
  return <main className="intro-screen"><div className="intro-glow" /><div className="intro-orbit intro-orbit-one" /><div className="intro-orbit intro-orbit-two" /><div className="intro-logo"><img src="/LOGO.jpeg" alt="Logo SGCI" /><span /><strong>PILOT</strong></div><div className="intro-wordmark"><span>SGCI</span><b>Piloté tout-en-un</b></div><div className="intro-loader"><i /><span>Initialisation de votre espace</span></div></main>
}

function LoginScreen({ onLogin }: { onLogin: () => Promise<void> }) {
  const [email, setEmail] = useState('superadmin@demo.com')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState('')

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setError('')
    setIsSubmitting(true)
    window.setTimeout(async () => {
      try {
        await demoAuth.signIn(email, password)
        await onLogin()
      } catch (loginError) {
        setError(loginError instanceof Error ? loginError.message : 'Impossible de se connecter.')
        setIsSubmitting(false)
      }
    }, 900)
  }

  return <main className="login-screen"><section className="login-visual"><div className="login-visual-top"><div className="login-mini-brand"><img src="/LOGO.jpeg" alt="SGCI SARLU" /><span /> <strong>PILOT</strong></div><span className="login-secure"><Icons.ShieldCheck size={14} /> Accès sécurisé</span></div><div className="login-orbit-scene"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit-dot dot-one" /><div className="orbit-dot dot-two" /><div className="login-logo-card"><img src="/LOGO.jpeg" alt="Logo SGCI" /><div className="logo-card-line" /><strong>PILOT</strong></div><div className="login-rings" /></div><div className="login-message"><p className="eyebrow">Votre centre de pilotage</p><h1>Piloté<br /><em>tout-en-un.</em></h1><p>Une vision claire de vos activités, de vos équipes et de votre croissance.</p><div className="login-progress"><i /><span>SGCI Pilot · Gestion intégrée</span></div></div><div className="login-visual-footer"><span>© 2026 SGCI SARLU</span><span>Gestion intégrée, simplement.</span></div></section><section className="login-form-panel"><div className="login-form-wrap"><div className="mobile-login-brand"><img src="/LOGO.jpeg" alt="SGCI SARLU" /><strong>PILOT</strong></div><div className="login-heading"><span className="login-kicker">Bienvenue dans votre espace</span><h2>Connectez-vous.</h2><p>Accédez à votre environnement de pilotage SGCI.</p></div><form className="login-form" onSubmit={handleSubmit}><label>Adresse email<div className="login-input"><Icons.Mail size={17} /><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="vous@entreprise.com" required /></div></label><label>Mot de passe<div className="login-input"><Icons.LockKeyhole size={17} /><input type={showPassword ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Saisissez votre mot de passe" required /><button type="button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? 'Masquer le mot de passe' : 'Afficher le mot de passe'}>{showPassword ? <Icons.EyeOff size={16} /> : <Icons.Eye size={16} />}</button></div></label>{error && <p className="login-error"><Icons.CircleAlert size={14} /> {error}</p>}<div className="login-options"><label className="remember"><input type="checkbox" /> <span>Se souvenir de moi</span></label><button type="button" className="forgot-password">Mot de passe oublié ?</button></div><button className={`login-submit ${isSubmitting ? 'loading' : ''}`} type="submit" disabled={isSubmitting}>{isSubmitting ? <><span className="login-spinner" /> Connexion en cours...</> : <>Se connecter <Icons.ArrowRight size={17} /></>}</button></form><div className="login-footer-note"><Icons.LockKeyhole size={13} /> Vos données sont protégées et chiffrées.</div></div><div className="login-help">Besoin d'aide ? <button type="button">Contacter le support</button></div></section></main>
}

function Brand() {
  return <div className="brand"><img src="/LOGO.jpeg" alt="SGCI SARLU" /><span className="brand-divider" /><span className="brand-product">PILOT</span></div>
}

function Sidebar({ active, onNavigate, onBuildingSelect, selectedBuilding, buildingsExpanded, onToggleBuildings, expandedGroups, onToggleGroup, open, onClose }: { active: ModuleKey; onNavigate: (key: ModuleKey) => void; onBuildingSelect: (id: string) => void; selectedBuilding: string | null; buildingsExpanded: boolean; onToggleBuildings: () => void; expandedGroups: Record<string, boolean>; onToggleGroup: (label: string) => void; open: boolean; onClose: () => void }) {
  return <>
    <div className={`sidebar-overlay ${open ? 'visible' : ''}`} onClick={onClose} />
    <aside className={`sidebar ${open ? 'open' : ''}`}>
      <div className="sidebar-top"><Brand /><button className="icon-button sidebar-close" onClick={onClose} aria-label="Fermer le menu"><Icons.X size={18} /></button></div>
      <div className="workspace-switcher"><div className="workspace-mark">S</div><div><strong>SGCI SARLU</strong><span>Organisation principale</span></div><Icons.ChevronsUpDown size={15} /></div>
      <nav className="nav-scroll">
        {navigation.map((group) => { const groupExpanded = expandedGroups[group.label] ?? true; return <div className="nav-group" key={group.label}><button type="button" className={`nav-label nav-group-toggle ${groupExpanded ? 'expanded' : ''}`} onClick={() => onToggleGroup(group.label)}><span>{group.label}</span><Icons.ChevronDown size={13} /></button>{groupExpanded && group.items.map((item) => { const Icon = iconMap[item.icon]; const isBuildings = item.key === 'buildings'; return <div key={item.key} className={isBuildings ? 'nav-tree' : ''}><div className={isBuildings ? 'nav-item-row' : ''}>{isBuildings ? <div className={`nav-item nav-item-static ${active === item.key ? 'active' : ''}`}><Icon size={17} strokeWidth={active === item.key ? 2.3 : 1.8} /><span>{item.label}</span></div> : <button className={`nav-item ${active === item.key ? 'active' : ''}`} key={item.key} onClick={() => { onNavigate(item.key); onClose() }}><Icon size={17} strokeWidth={active === item.key ? 2.3 : 1.8} /><span>{item.label}</span>{item.badge && <em>{item.badge}</em>}</button>}{isBuildings && <button type="button" className={`nav-chevron-button ${buildingsExpanded ? 'expanded' : ''}`} onClick={onToggleBuildings} aria-label={buildingsExpanded ? 'Fermer la liste des immeubles' : 'Ouvrir la liste des immeubles'}><Icons.ChevronDown size={14} /></button>}</div>{isBuildings && buildingsExpanded && <div className="building-subnav"><button className={selectedBuilding === 'IMM-001' ? 'selected' : ''} onClick={() => onBuildingSelect('IMM-001')}><span className="subnav-dot green" />Horizon 6</button><button className={selectedBuilding === 'IMM-002' ? 'selected' : ''} onClick={() => onBuildingSelect('IMM-002')}><span className="subnav-dot blue" />Horizon 4</button></div>}</div> })}</div> })}
      </nav>
      <div className="sidebar-footer"><div className="support-card"><span className="support-icon"><Icons.LifeBuoy size={16} /></span><div><strong>Besoin d'aide ?</strong><span>Consulter le centre d'aide</span></div><Icons.ArrowUpRight size={15} /></div><div className="sidebar-version">SGCI Pilot <span>v0.1.0</span></div></div>
    </aside>
  </>
}

function Header({ onMenu, onSignOut, sidebarOpen, darkMode, onToggleTheme }: { onMenu: () => void; onSignOut: () => void; sidebarOpen: boolean; darkMode: boolean; onToggleTheme: () => void }) {
  return <header className="topbar"><button className="icon-button menu-button" onClick={onMenu} aria-label={sidebarOpen ? 'Fermer le menu' : 'Ouvrir le menu'}>{sidebarOpen ? <Icons.X size={20} /> : <Icons.Menu size={20} />}</button><div className="breadcrumb"><span>SGCI Pilot</span><Icons.ChevronRight size={14} /><strong>Tableau de bord</strong></div><div className="topbar-actions"><label className="search"><Icons.Search size={17} /><input placeholder="Rechercher..." /><kbd>⌘ K</kbd></label><button className="theme-toggle" onClick={onToggleTheme} aria-label={darkMode ? 'Activer le mode clair' : 'Activer le mode nuit'} title={darkMode ? 'Mode clair' : 'Mode nuit'}>{darkMode ? <Icons.Sun size={17} /> : <Icons.Moon size={17} />}</button><button className="icon-button notification" aria-label="Notifications"><Icons.Bell size={19} /><i /></button><div className="profile"><div className="avatar">JV</div><div className="profile-text"><strong>Jean Vecko</strong><span>Super administrateur</span></div><Icons.ChevronDown size={15} /></div><button className="sign-out-button" onClick={onSignOut} aria-label="Se déconnecter" title="Se déconnecter"><Icons.LogOut size={16} /><span>Déconnexion</span></button></div></header>
}

function StatCard({ stat }: { stat: typeof stats[number] }) {
  const icons = { gold: Icons.Building2, blue: Icons.DoorOpen, green: Icons.Users, red: Icons.FileWarning }
  const Icon = icons[stat.tone]
  return <article className="stat-card"><div className={`stat-icon ${stat.tone}`}><Icon size={19} /></div><div className="stat-copy"><span>{stat.label}</span><strong>{stat.value}</strong><small className={stat.trend === 'down' ? 'negative' : stat.trend === 'neutral' ? 'neutral' : ''}>{stat.trend === 'up' && <Icons.TrendingUp size={13} />}{stat.trend === 'neutral' && <Icons.Clock3 size={13} />}{stat.change}</small></div><button className="more-button" aria-label={`Options ${stat.label}`}><Icons.MoreHorizontal size={18} /></button></article>
}

function Dashboard({ onNavigate }: { onNavigate: (key: ModuleKey) => void }) {
  const syncIconMap = { 'building-2': Icons.Building2, boxes: Icons.Boxes, 'calendar-check-2': Icons.CalendarCheck2, 'folder-open': Icons.FolderOpen }
  return <div className="page-content dashboard-page"><section className="page-heading"><div><p className="eyebrow">Pilotage global · Mardi 15 septembre 2026</p><h1>Bonjour Jean</h1><p className="heading-copy">Voici la situation consolidée de tous vos services aujourd'hui.</p></div><button className="primary-button" onClick={() => onNavigate('reports')}><Icons.BarChart3 size={17} /> Voir les rapports</button></section>
    <section className="stats-grid">{stats.map((stat) => <StatCard key={stat.label} stat={stat} />)}</section>
    <section className="dashboard-grid"><article className="panel performance-panel"><div className="panel-heading"><div><p className="eyebrow">Vue financière</p><h2>Trésorerie & activité</h2></div><button className="select-button">Cette année <Icons.ChevronDown size={14} /></button></div><div className="finance-summary"><div><span>Solde disponible</span><strong>$ 8 450 000</strong><p className="positive"><Icons.TrendingUp size={14} /> 12,8% <span>vs mois dernier</span></p></div><div className="legend"><span><i className="legend-dot revenue" /> Revenus</span><span><i className="legend-dot expense" /> Dépenses</span></div></div><div className="chart"><div className="chart-y"><span>10M</span><span>7,5M</span><span>5M</span><span>2,5M</span><span>0</span></div><div className="chart-area"><div className="grid-lines"><i /><i /><i /><i /><i /></div><svg viewBox="0 0 700 190" preserveAspectRatio="none" aria-label="Graphique des revenus et dépenses"><defs><linearGradient id="revenue-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#b26b0b" stopOpacity=".18" /><stop offset="1" stopColor="#b26b0b" stopOpacity="0" /></linearGradient></defs><path d="M0 145 C35 125 65 132 98 108 S157 92 192 105 S252 70 291 87 S355 70 386 64 S445 77 484 50 S535 60 576 39 S634 52 700 20 L700 190 L0 190 Z" fill="url(#revenue-fill)" /><path d="M0 145 C35 125 65 132 98 108 S157 92 192 105 S252 70 291 87 S355 70 386 64 S445 77 484 50 S535 60 576 39 S634 52 700 20" fill="none" stroke="#b26b0b" strokeWidth="3" strokeLinecap="round" /><path d="M0 167 C48 151 72 155 112 145 S165 132 202 147 S260 119 298 130 S345 113 390 122 S448 106 484 115 S535 98 572 108 S628 86 700 96" fill="none" stroke="#96a3aa" strokeWidth="2.5" strokeDasharray="5 6" strokeLinecap="round" /></svg><div className="chart-x"><span>Jan</span><span>Fév</span><span>Mar</span><span>Avr</span><span>Mai</span><span>Juin</span><span>Juil</span><span>Aoû</span><span>Sep</span><span>Oct</span><span>Nov</span><span>Déc</span></div></div></div></article>
      <article className="panel alerts-panel"><div className="panel-heading"><div><p className="eyebrow">À surveiller</p><h2>Alertes</h2></div><button className="text-button">Tout voir <Icons.ArrowUpRight size={15} /></button></div><div className="alert-list"><div className="alert-row"><span className="alert-symbol warning"><Icons.AlertTriangle size={17} /></span><div><strong>3 contrats arrivent à échéance</strong><span>Dans les 30 prochains jours</span></div><Icons.ChevronRight size={16} /></div><div className="alert-row"><span className="alert-symbol danger"><Icons.PackageX size={17} /></span><div><strong>Stock faible au Dépôt B</strong><span>8 articles sous le seuil minimum</span></div><Icons.ChevronRight size={16} /></div><div className="alert-row"><span className="alert-symbol info"><Icons.Wrench size={17} /></span><div><strong>2 interventions en attente</strong><span>Résidence Les Jardins</span></div><Icons.ChevronRight size={16} /></div></div><div className="alert-footer"><span>Dernière mise à jour</span><strong>Il y a 4 min</strong></div></article>
    </section>
    <section className="lower-grid"><article className="panel sync-panel"><div className="panel-heading"><div><p className="eyebrow">Vue interservices</p><h2>Synchronisation majeure</h2></div><button className="text-button" onClick={() => onNavigate('activity')}>Voir le journal <Icons.ArrowUpRight size={15} /></button></div><div className="sync-list">{serviceSync.map((item) => { const SyncIcon = syncIconMap[item.icon as keyof typeof syncIconMap]; return <div className="sync-row" key={item.title}><span className={`sync-icon ${item.tone}`}><SyncIcon size={16} /></span><div className="sync-info"><div><strong>{item.title}</strong><span>{item.service} · {item.detail}</span></div><small>{item.time}</small></div><span className={`sync-status ${item.status === 'Synchronisé' ? 'done' : 'pending'}`}><Icons.CheckCircle2 size={12} /> {item.status}</span></div> })}</div></article><article className="panel occupancy-panel"><div className="panel-heading"><div><p className="eyebrow">Immobilier</p><h2>Occupation</h2></div><button className="more-button" aria-label="Options occupation"><Icons.MoreHorizontal size={18} /></button></div><div className="occupancy-body"><div className="donut"><div><strong>86</strong><span>unités</span></div></div><div className="occupancy-legend"><div><span><i className="dot occupied" /> Occupés</span><strong>74 <small>86%</small></strong></div><div><span><i className="dot available" /> Disponibles</span><strong>8 <small>9%</small></strong></div><div><span><i className="dot maintenance" /> Maintenance</span><strong>4 <small>5%</small></strong></div></div></div></article></section>
  </div>
}

function ModulePage({ module, onNavigate }: { module: ModuleKey; onNavigate: (key: ModuleKey) => void }) {
  const meta = moduleMeta[module] ?? moduleMeta.dashboard
  const Icon = iconMap[navigation.flatMap((group) => group.items).find((item) => item.key === module)?.icon ?? 'layout-dashboard']
  return <div className="page-content module-page"><section className="page-heading"><div><p className="eyebrow">{meta.eyebrow}</p><h1>{meta.title}</h1><p className="heading-copy">{meta.description}</p></div><button className="primary-button"><Icons.Plus size={17} /> Nouvelle entrée</button></section><div className="module-toolbar"><label className="table-search"><Icons.Search size={16} /><input placeholder={`Rechercher dans ${meta.title.toLowerCase()}...`} /></label><button className="filter-button"><Icons.SlidersHorizontal size={16} /> Filtres <span>0</span></button><button className="filter-button"><Icons.Download size={16} /> Exporter</button></div><section className="module-empty panel"><div className="empty-icon"><Icon size={25} /></div><h2>Votre espace {meta.title.toLowerCase()}</h2><p>Cette vue est prête à accueillir vos données et vos workflows. La structure est en place pour connecter votre API et enrichir ce module progressivement.</p><button className="secondary-button" onClick={() => onNavigate('dashboard')}><Icons.ArrowLeft size={16} /> Retour au tableau de bord</button></section></div>
}

function BuildingDetail({ buildingId, onBack }: { buildingId: string; onBack: () => void }) {
  const building = buildingDetails[buildingId as keyof typeof buildingDetails] ?? buildingDetails['IMM-001']
  return <div className="page-content building-detail-page"><button className="back-link" onClick={onBack}><Icons.ArrowLeft size={15} /> Tous les immeubles</button><section className="detail-heading"><div><p className="eyebrow">Immobilier · Immeuble</p><h1>{building.name}</h1><p className="heading-copy"><Icons.MapPin size={14} /> {building.address}</p></div><button className="primary-button"><Icons.Download size={16} /> Télécharger le contrat PDF</button></section><section className="building-detail-kpis"><article className="panel detail-kpi"><span className="detail-kpi-icon blue"><Icons.DoorOpen size={18} /></span><div><small>Nombre de chambres</small><strong>{building.rooms}</strong></div></article><article className="panel detail-kpi"><span className="detail-kpi-icon green"><Icons.Users size={18} /></span><div><small>Chambres occupées</small><strong>{building.occupied}<em> / {building.rooms}</em></strong></div></article><article className="panel detail-kpi"><span className="detail-kpi-icon gold"><Icons.CircleDollarSign size={18} /></span><div><small>Garantie</small><strong>{building.guarantee}</strong></div></article><article className="panel detail-kpi"><span className="detail-kpi-icon purple"><Icons.CalendarClock size={18} /></span><div><small>Paiement mensuel</small><strong>{building.monthlyPayment}</strong></div></article></section><section className="building-detail-grid"><article className="panel client-detail-panel"><div className="panel-heading"><div><p className="eyebrow">Occupation principale</p><h2>Profil du client</h2></div><span className="detail-status">Contrat actif</span></div><div className="client-profile"><div className="client-avatar">{building.clientInitials}</div><div><strong>{building.client}</strong><span>{building.clientPhone}</span></div></div><div className="client-fields"><div><span>Montant de la garantie</span><strong>{building.guarantee}</strong></div><div><span>Paiement mensuel</span><strong>{building.monthlyPayment}</strong></div><div><span>Début du contrat</span><strong>{building.contractStart}</strong></div><div><span>Fin du contrat</span><strong>{building.contractEnd}</strong></div></div></article><article className="panel availability-detail-panel"><div className="panel-heading"><div><p className="eyebrow">État de l’immeuble</p><h2>Occupation</h2></div><button className="more-button" aria-label="Options de l'immeuble"><Icons.MoreHorizontal size={18} /></button></div><div className="detail-occupancy"><div className="detail-donut"><strong>{Math.round((building.occupied / building.rooms) * 100)}%</strong><span>occupé</span></div><div className="detail-legend"><div><span><i className="dot occupied" /> Occupées</span><strong>{building.occupied}</strong></div><div><span><i className="dot available" /> Disponibles</span><strong>{building.available}</strong></div></div></div></article></section></div>
}

function BuildingsPage({ onNavigate, selectedBuilding, onBuildingSelect }: { onNavigate: (key: ModuleKey) => void; selectedBuilding: string | null; onBuildingSelect: (id: string) => void }) {
  if (selectedBuilding) return <BuildingDetail buildingId={selectedBuilding} onBack={() => onBuildingSelect('')} />
  return <div className="page-content buildings-page"><section className="page-heading"><div><p className="eyebrow">Immobilier</p><h1>Immeubles</h1><p className="heading-copy">Sélectionnez un immeuble dans la liste pour consulter son détail.</p></div><button className="primary-button"><Icons.Plus size={17} /> Ajouter un immeuble</button></section>
    <section className="building-kpis"><article className="building-kpi panel"><span className="building-kpi-icon gold"><Icons.Building2 size={18} /></span><div><small>Immeubles enregistrés</small><strong>12</strong><em><Icons.TrendingUp size={12} /> +2 ce mois</em></div></article><article className="building-kpi panel"><span className="building-kpi-icon blue"><Icons.LayoutGrid size={18} /></span><div><small>Unités au total</small><strong>86</strong><em className="neutral-kpi">74 occupées</em></div></article><article className="building-kpi panel"><span className="building-kpi-icon green"><Icons.Percent size={18} /></span><div><small>Taux d’occupation</small><strong>86%</strong><em><Icons.TrendingUp size={12} /> +4,2% ce mois</em></div></article><article className="building-kpi panel"><span className="building-kpi-icon purple"><Icons.CircleDollarSign size={18} /></span><div><small>Revenus mensuels</small><strong>$ 47 250</strong><em className="neutral-kpi">4 immeubles actifs</em></div></article></section>
    <section className="panel buildings-list-panel"><div className="panel-heading"><div><p className="eyebrow">Parc immobilier</p><h2>Vos immeubles</h2></div><button className="filter-button"><Icons.SlidersHorizontal size={15} /> Filtres <span>0</span></button></div><div className="buildings-toolbar"><label className="table-search"><Icons.Search size={16} /><input placeholder="Rechercher un immeuble..." /></label><button className="filter-button"><Icons.ListFilter size={15} /> Tous les statuts <Icons.ChevronDown size={13} /></button><button className="filter-button"><Icons.LayoutGrid size={15} /></button></div><div className="building-table-wrap"><table className="building-table"><thead><tr><th>Immeuble</th><th>Localisation</th><th>Occupation</th><th>Revenus / mois</th><th>Statut</th><th>Mise à jour</th><th /></tr></thead><tbody>{buildings.map((building) => <tr key={building.id} onClick={() => onBuildingSelect(building.id)}><td><div className="building-name"><span className={`building-avatar ${building.tone}`}><Icons.Building2 size={17} /></span><div><strong>{building.name}</strong><small>{building.id}</small></div></div></td><td><strong>{building.city}</strong><small>{building.address}</small></td><td><div className="occupancy-cell"><div className="occupancy-label"><strong>{building.occupied}/{building.units}</strong><span>{Math.round((building.occupied / building.units) * 100)}%</span></div><div className="mini-track"><i style={{ width: `${(building.occupied / building.units) * 100}%` }} /></div></div></td><td><strong className="building-revenue">{building.monthlyRevenue}</strong></td><td><span className={`building-status ${building.tone}`}>{building.status}</span></td><td>{building.updatedAt}</td><td><button className="more-button" aria-label={`Options ${building.name}`}><Icons.MoreHorizontal size={18} /></button></td></tr>)}</tbody></table></div></section><div className="building-note"><Icons.Info size={15} /><span>La liste est aussi disponible sous le menu Immeubles pour un accès direct.</span><button className="text-button" onClick={() => onNavigate('dashboard')}>Retour au tableau de bord <Icons.ArrowUpRight size={14} /></button></div>
  </div>
}

function EventDashboard({ onNavigate }: { onNavigate: (key: ModuleKey) => void }) {
  return <div className="page-content event-dashboard"><section className="page-heading"><div><p className="eyebrow">Espace événementiel · Septembre 2026</p><h1>Tableau de bord événementiel</h1><p className="heading-copy">Suivez l’activité, les revenus et les disponibilités de vos deux espaces.</p></div><button className="primary-button" onClick={() => onNavigate('event-reservations')}><Icons.Plus size={17} /> Nouvelle réservation</button></section>
    <section className="event-kpis"><article className="event-kpi panel"><span className="kpi-icon gold"><Icons.CircleDollarSign size={18} /></span><div><small>Revenus du mois</small><strong>$ 11 090</strong><em><Icons.TrendingUp size={12} /> 18,4% vs août</em></div></article><article className="event-kpi panel"><span className="kpi-icon blue"><Icons.CalendarCheck2 size={18} /></span><div><small>Réservations confirmées</small><strong>19</strong><em><Icons.CheckCircle2 size={12} /> 4 cette semaine</em></div></article><article className="event-kpi panel"><span className="kpi-icon green"><Icons.BadgeDollarSign size={18} /></span><div><small>Montants encaissés</small><strong>$ 8 740</strong><em><Icons.TrendingUp size={12} /> 79% du facturé</em></div></article><article className="event-kpi panel"><span className="kpi-icon purple"><Icons.CalendarClock size={18} /></span><div><small>Prochaine disponibilité</small><strong>16 sept.</strong><em className="muted-kpi">Les deux espaces libres</em></div></article></section>
    <section className="event-main-grid"><article className="panel space-revenue-panel"><div className="panel-heading"><div><p className="eyebrow">Performance par espace</p><h2>Revenus mensuels</h2></div><button className="select-button">Septembre 2026 <Icons.ChevronDown size={14} /></button></div><div className="space-revenue-list">{eventSpaces.map((space) => <div className="space-revenue-row" key={space.name}><div className={`space-mark ${space.tone}`}><Icons.Building2 size={18} /></div><div className="space-revenue-info"><div><strong>{space.name}</strong><span>{space.reservations} réservations · {space.occupancy} occupé</span></div><b>{space.revenue}</b><div className="revenue-track"><i className={space.tone} style={{ width: space.tone === 'gold' ? '82%' : '67%' }} /></div></div></div>)}</div><div className="space-revenue-total"><span>Total des espaces</span><strong>$ 11 090</strong></div></article><article className="panel availability-panel"><div className="panel-heading"><div><p className="eyebrow">Planning</p><h2>Disponibilités</h2></div><button className="more-button" aria-label="Options du calendrier"><Icons.MoreHorizontal size={18} /></button></div><div className="calendar-nav"><button className="icon-button" aria-label="Mois précédent"><Icons.ChevronLeft size={16} /></button><strong>Septembre 2026</strong><button className="icon-button" aria-label="Mois suivant"><Icons.ChevronRight size={16} /></button></div><div className="calendar-grid"><div className="calendar-weekdays">{['Lu', 'Ma', 'Me', 'Je', 'Ve', 'Sa', 'Di'].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar-days">{eventCalendar.map((item) => <span className={`calendar-day ${item.status}`} key={item.day}>{item.day}</span>)}</div></div><div className="calendar-legend"><span><i className="available-dot" /> Disponible</span><span><i className="partial-dot" /> Partiel</span><span><i className="booked-dot" /> Réservé</span></div></article></section>
    <section className="panel reservations-panel"><div className="panel-heading"><div><p className="eyebrow">Suivi des encaissements</p><h2>Réservations à venir</h2></div><button className="text-button" onClick={() => onNavigate('event-reservations')}>Voir toutes les réservations <Icons.ArrowUpRight size={15} /></button></div><div className="reservation-table-wrap"><table className="reservation-table"><thead><tr><th>Date</th><th>Événement</th><th>Espace</th><th>Client</th><th>Montant</th><th>Payé</th><th>Statut</th></tr></thead><tbody>{eventReservations.map((reservation) => <tr key={reservation.date + reservation.title}><td><strong>{reservation.date}</strong><span>{reservation.day}</span></td><td><strong>{reservation.title}</strong></td><td><span className="space-tag"><i className={reservation.tone} />{reservation.space}</span></td><td>{reservation.client}</td><td>{reservation.amount}</td><td className={reservation.paid === '$ 0' ? 'unpaid' : ''}>{reservation.paid}</td><td><span className={`status-pill ${reservation.tone}`}>{reservation.status}</span></td></tr>)}</tbody></table></div></section>
  </div>
}

export default function App() {
  const [showIntro, setShowIntro] = useState(true)
  const [authenticated, setAuthenticated] = useState(() => localStorage.getItem('sgci-authenticated') === 'true')
  const [active, setActive] = useState<ModuleKey>('dashboard')
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [selectedBuilding, setSelectedBuilding] = useState<string | null>(null)
  const [buildingsExpanded, setBuildingsExpanded] = useState(false)
  const [expandedGroups, setExpandedGroups] = useState<Record<string, boolean>>(() => Object.fromEntries(navigation.map((group) => [group.label, group.label === 'Pilotage'])))
  const [darkMode, setDarkMode] = useState(() => localStorage.getItem('sgci-theme') !== 'light')

  useEffect(() => {
    const introTimer = window.setTimeout(() => setShowIntro(false), 3000)
    return () => window.clearTimeout(introTimer)
  }, [])

  useEffect(() => {
    document.documentElement.dataset.theme = darkMode ? 'dark' : 'light'
    localStorage.setItem('sgci-theme', darkMode ? 'dark' : 'light')
  }, [darkMode])

  if (showIntro) return <IntroScreen />
  if (!authenticated) return <LoginScreen onLogin={async () => { localStorage.setItem('sgci-authenticated', 'true'); setAuthenticated(true) }} />

  return <div className="app-shell"><Sidebar active={active} onNavigate={(key) => { setActive(key); if (key !== 'buildings') { setSelectedBuilding(null); setBuildingsExpanded(false) } }} onBuildingSelect={(id) => { setActive('buildings'); setSelectedBuilding(id || null) }} selectedBuilding={selectedBuilding} buildingsExpanded={buildingsExpanded} onToggleBuildings={() => setBuildingsExpanded((value) => !value)} expandedGroups={expandedGroups} onToggleGroup={(label) => setExpandedGroups((groups) => ({ ...groups, [label]: !groups[label] }))} open={sidebarOpen} onClose={() => setSidebarOpen(false)} /><main className="main-area"><Header onMenu={() => setSidebarOpen((value) => !value)} onSignOut={() => { demoAuth.signOut(); localStorage.removeItem('sgci-authenticated'); setAuthenticated(false) }} sidebarOpen={sidebarOpen} darkMode={darkMode} onToggleTheme={() => setDarkMode((value) => !value)} />{active === 'dashboard' ? <Dashboard onNavigate={setActive} /> : active === 'buildings' ? <BuildingsPage onNavigate={setActive} selectedBuilding={selectedBuilding} onBuildingSelect={(id) => setSelectedBuilding(id || null)} /> : active === 'events' ? <EventDashboard onNavigate={setActive} /> : <ModulePage module={active} onNavigate={setActive} />}</main></div>
}
